# Form implementation generated from reading ui file '/workspaces/ros2/src/qrobot_server/qrobot_server/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(759, 627)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/workspaces/ros2/src/qrobot_server/qrobot_server/icons/robot.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 320))
        self.tabWidget.setObjectName("tabWidget")
        self.tabCamera = QtWidgets.QWidget()
        self.tabCamera.setObjectName("tabCamera")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tabCamera)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gv_camera = QtWidgets.QGraphicsView(parent=self.tabCamera)
        self.gv_camera.setObjectName("gv_camera")
        self.gridLayout_3.addWidget(self.gv_camera, 0, 0, 1, 1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/workspaces/ros2/src/qrobot_server/qrobot_server/../../../../../home/vscode/robot/qrobot/icons/eye.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tabWidget.addTab(self.tabCamera, icon1, "")
        self.tabServos = QtWidgets.QWidget()
        self.tabServos.setObjectName("tabServos")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tabServos)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.tabServos)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.sa_servos = QtWidgets.QWidget()
        self.sa_servos.setGeometry(QtCore.QRect(0, 0, 717, 302))
        self.sa_servos.setObjectName("sa_servos")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.sa_servos)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gl_servos = QtWidgets.QGridLayout()
        self.gl_servos.setObjectName("gl_servos")
        self.gridLayout_5.addLayout(self.gl_servos, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.sa_servos)
        self.gridLayout_4.addWidget(self.scrollArea, 0, 0, 1, 1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("/workspaces/ros2/src/qrobot_server/qrobot_server/../../../../../home/vscode/.designer/icons/arm.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tabWidget.addTab(self.tabServos, icon2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.teLog = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.teLog.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.teLog.setReadOnly(True)
        self.teLog.setObjectName("teLog")
        self.gridLayout.addWidget(self.teLog, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(parent=MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.actionConfig = QtGui.QAction(parent=MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("/workspaces/ros2/src/qrobot_server/qrobot_server/icons/gear.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionConfig.setIcon(icon3)
        self.actionConfig.setObjectName("actionConfig")
        self.actionExit = QtGui.QAction(parent=MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("/workspaces/ros2/src/qrobot_server/qrobot_server/icons/quit.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionExit.setIcon(icon4)
        self.actionExit.setObjectName("actionExit")
        self.toolBar.addAction(self.actionConfig)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExit)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.actionExit.triggered.connect(MainWindow.close) # type: ignore
        self.actionConfig.triggered.connect(MainWindow.on_config) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Робот"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCamera), _translate("MainWindow", "Камера"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabServos), _translate("MainWindow", "Сервоприводы"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionConfig.setText(_translate("MainWindow", "Настройки"))
        self.actionConfig.setStatusTip(_translate("MainWindow", "Открыть окно настроек робота"))
        self.actionExit.setText(_translate("MainWindow", "Выход"))
        self.actionExit.setStatusTip(_translate("MainWindow", "Завершить работу"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+X"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
